# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Walter Dempsey
tagline:             ' Statistican / Data Scientist'
description:         'A postdoctoral researcher in the <a href="http://people.seas.harvard.edu/~samurphy/lab/overview.html" target="_blank">Statistical Reinforcement Lab</a> at Harvard University <a href="stat.harvard.edu/" target="_blank">Statistics department</a>.'
url:                 http://plusthemonk.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Walter Dempsey
  url:               https://github.com/PlusTheMonk
  email:             wdempsey@fas.harvard.edu

# Custom vars
version:             1.0.0
